server:
    port: 5000
spring:
    jpa:
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        ddl-auto: update
    datasource: 
      url: jdbc:mysql://awseb-e-gkhnapdt3x-stack-awsebrdsdatabase-vjto5donzzhd.c1u4y20ygl3s.ap-northeast-2.rds.amazonaws.com:3306/ebdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      username: textpm
      password: 11111111